import mongoose, { Schema, type Document } from "mongoose";

export interface ITokenUsage extends Document {
  userId: string;
  username: string;
  /** Which subject/feature triggered this request */
  subject: string;
  /** The model/deployment used */
  modelName: string;
  /** Tokens consumed by the prompt (input) */
  promptTokens: number;
  /** Tokens generated by the completion (output) */
  completionTokens: number;
  /** Total tokens (prompt + completion) */
  totalTokens: number;
  /** Optional: the associated chat session ID */
  chatId?: string;
  /** Optional: the API route that handled the request */
  endpoint: string;
  createdAt: Date;
}

const TokenUsageSchema = new Schema<ITokenUsage>(
  {
    userId: { type: String, required: true, index: true },
    username: { type: String, required: true },
    subject: { type: String, required: true, index: true },
    modelName: { type: String, required: true },
    promptTokens: { type: Number, required: true, default: 0 },
    completionTokens: { type: Number, required: true, default: 0 },
    totalTokens: { type: Number, required: true, default: 0 },
    chatId: { type: String },
    endpoint: { type: String, required: true },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

TokenUsageSchema.index({ createdAt: -1 });
TokenUsageSchema.index({ userId: 1, createdAt: -1 });
TokenUsageSchema.index({ subject: 1, createdAt: -1 });

export const TokenUsage =
  (mongoose.models.TokenUsage as mongoose.Model<ITokenUsage> | undefined) ??
  mongoose.model<ITokenUsage>("TokenUsage", TokenUsageSchema);
